### ISSUE TITLE
Deprecated option - Error in HA supervisor logs

### ISSUE THREAD

**Issue by SNoof85** [Sabuto/hassio-jackett#14]
If you are experiencing an issue with the search or indexing of a tracker check out the issue registry on the Jacket github (https://github.com/Jackett/Jackett/issues).
If you are experiencing bugs or issues with the add-on crashing or similar 

# Issue

Issue with log entry in HA Supervisor

## Expected behaviour

No errors 😋 

## Actual behaviour

Error !

## Steps to reproduce
Add the addon repo to your HA instance. Don't even need to install the addon

## Proposed changes

See #15 

## Logs

> (Paste any relevant log details here)

`21-03-31 11:47:46 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'startup' with 'before' is deprecated. Please report this to the maintainer of Jackett`

**Comment by SNoof85** [comment]
edited to match the template, sorry !

**Comment by sabuto** [comment]
Thanks for this :), i didnt realise all the repo's affected this if not using them. I will push a release now. Glad you like the telegraf plugin :D

**Comment by joselcaguilar** [comment]
Hi @Sabuto I have added the repo to the add-ons store in Home Assistant OS and I can still see the warning message reported by @SNoof85, even though Telegraf and/or Jackett are not installed! Do you have a plan to release this fix @Sabuto? Thanks in advance for your hard work! :)

**Comment by sabuto** [comment]
> 
> 
> Hi @Sabuto I have added the repo to the add-ons store in Home Assistant OS and I can still see the warning message reported by @SNoof85, even though Telegraf and/or Jackett are not installed! Do you have a plan to release this fix @Sabuto? Thanks in advance for your hard work! :)

Hey sorry I thought i'd done this. I will try and push tomorrow

**Comment by sabuto** [comment]
Sorry for the delay i've pushed it to the main repo, can you guys double check to see if its working as should be @SNoof85 @joselcaguilar

**Comment by joselcaguilar** [comment]
It's working as expected, thanks @Sabuto 🎉
